<!DOCTYPE html>
<html lang="fr">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Connexion</title>
</head>
<body>


<form class="form">
        <legend></legend>
        <div class="form-group">
            <input type="email" name="email" class="form-control" id="email" aria-describedby="emailHelp" placeholder="Adresse email">
        </div>
        <div class="form-group">
            <input type="password" name="mdp" class="form-control" id="password" placeholder="Mot de passe">
        </div>
        <button type="submit" class="btn btn-primary btn1">Se connecter</button>
    </form>

    <div class="test"></div>

</body>
<script src="https://code.jquery.com/jquery-3.3.1.js" ></script>
<script src="main.js"></script>
</html>