<!DOCTYPE html>
<html lang="fr">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <!--<link rel="stylesheet" href="style.css"> -->
    <title>Connexion</title>
</head>
<body>  

    <form method="POST" class="form2">
        <legend>Nous écrire</legend>
            <div class="form-group col-md-11">
                <input name="mail" type="mail" class="form-control" id="emailContact" placeholder="Adresse email">
            </div>
            <div>
                <textarea name="texte" id="texte" placeholder="Votre message">
                </textarea>
            </div>
            

       <button type="submit" class="btn btn-primary">Envoyer</button>
     </form>

</body>
<script src="https://code.jquery.com/jquery-3.3.1.js" ></script>
<script src="main.js"></script>
</html>