<!DOCTYPE html>
<html lang="fr">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <!--<link rel="stylesheet" href="style.css"> -->
    <title>Connexion</title>
</head>
<body>  

    <form method="POST" action="formulaire.php" class="form1">
        <legend>Créez votre compte</legend>
        <div class="form-group col-md-11">
           <label for="mail" class="sr-only">Email</label>
           <input name="mail" type="mail" class="form-control" id="mail" placeholder="Email address">
        </div>
        <div class="form-row">
            <div class="col-md-6">
               <label class="sr-only" for="inlineFormInput">Prénom</label>
               <input name="prenom" type="text" class="form-control mb-2" id="prenom" placeholder="Votre prénom">
            </div>
            <div class="col-md-6">
               <label class="sr-only" for="nom">Nom</label>
               <input name="nom" type="text" class="form-control mb-2" id="nom" placeholder="Votre nom">
            </div>
            <div class="form-group">
                <label for="mdp" class="sr-only">Choisissez un mot de passe</label>
                <input type="password" name="mdp" class="form-control" id="mdp" placeholder="Mot de passe">
            </div>

       <button type="submit" class="btn btn-primary">Enregistrer</button>
     </form>

</body>
<script src="https://code.jquery.com/jquery-3.3.1.js" ></script>
<script src="main.js"></script>
</html>