<main id="connexion">
    <div class="entete"></div>
    <h1 class="text-uppercase">Creer un compte utilisateur</h1>
    <p>Créer votre compte utilisateur vous permettra d'enregistrer vos recettes favorites !</p>
    <form class="create" method="POST" action="newUser.php">
        <input type="text" name="email" id="email" aria-describedby="emailHelp" placeholder="Adresse email">
        <input type="password" name="mdp" id="password" placeholder="Mot de passe">
        <input type="text" name="nom" id="nom" placeholder="Nom">
        <input type="text" name="prenom" id="prenom" placeholder="Prénom">
        <input type="submit" name="creation" value="Créer un nouvel utilisateur">
    </form>
    <div class="failed"></div>
</main>