<!DOCTYPE html>
<html lang="fr">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.6.1/css/all.css" integrity="sha384-gfdkjb5BdAXd+lj+gudLWI+BXq4IuLW5IT+brZEZsLFm++aCMlF1V92rMkPaX4PP" crossorigin="anonymous">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css">
    <link href="https://fonts.googleapis.com/css?family=Montserrat:400,800|Nixie+One" rel="stylesheet">
    <link rel="stylesheet" href="css/str.css">
    <title>Recettes</title>
</head>
<body>
    
<main id="recettes" class="container">
    <section id="presentation">
        <div class="image col-6">
        </div>
        <div class="titre col-6">
            <h1>Nos recettes</h1>
        </div>
        <div class="para">
            <p>Des recettes simples, à réaliser chez vous. Petits-déjeuners, gôuters, nos recettes originales raviront les plus petits comme les plus grands.</p>
            <p>Nos recettes sont faites avec des fruits bio, ce n'est pas indispensable mais nous vous le recommandons. IL est également préférable d'utiliser des fruits de saison.</p>
        </div>
        <a href=""><i class="far fa-heart"></i> Vos recettes favorites</a>
    </section>

    <section id="articles" class="row">
        <article class="col-sm-12 col-md-6 col-xl-4">
            <div style="background-image:url(img/photos/jus-ananas-orange.jpg)">
            </div>
                <h2><span>Orange gourmandise</span></h2>
        </article>
        <article class="col-sm-12 col-md-6 col-xl-4">
            <div style="background-image:url(img/photos/smoothie-detox-2.jpg)">
            </div>
            <h2><span>Pink pleasure</span></h2>
        </article>
        <article class="col-sm-12 col-md-6 col-xl-4">
            <div style="background-image:url(img/photos/smoothie-detox.jpg)">
            </div>
            <h2><span>Green Oxydant</span></h2>
        </article>
        <article class="col-sm-12 col-md-6 col-xl-4">
            <div style="background-image:url(img/photos/batido-detox-de-espinacas-kiwi-y-naranja.jpg)">
            </div>
            <h2><span>Smoothie détox</span></h2>
        </article>
        <article class="col-sm-12 col-md-6 col-xl-4">
            <div style="background-image:url(img/photos/Recette_CANDIA_Smoothie_exotique.jpg)">
            </div>
            <h2><span>Yellow Banana Mango</span></h2>
        </article>
        <article class="col-sm-12 col-md-6 col-xl-4">
            <div style="background-image:url(img/photos/watermelon_smoothie.jpg)">
            </div>
            <h2><span>Watermelon detox</span></h2>
        </article>
    </section>
</main>


</body>
</html>