<!DOCTYPE html>
<html lang="fr">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.6.1/css/all.css" integrity="sha384-gfdkjb5BdAXd+lj+gudLWI+BXq4IuLW5IT+brZEZsLFm++aCMlF1V92rMkPaX4PP" crossorigin="anonymous">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css">
    <link href="https://fonts.googleapis.com/css?family=Montserrat:400,800|Nixie+One" rel="stylesheet">
    <link rel="stylesheet" href="css/swag.css">
    <title>Recettes</title>
</head>
<body>
    
<main id="recettes" class="container">
    <section id="presentation">
        <div class="image col-6">
        </div>
        <div class="titre col-6">
            <h1>Nos recettes</h1>
        </div>
        <div class="para">
            <p>Des recettes simples, à réaliser chez vous. Petits-déjeuners, gôuters, nos recettes originales raviront les plus petits comme les plus grands.</p>
            <p>Nos recettes sont faites avec des fruits bio, ce n'est pas indispensable mais nous vous le recommandons. IL est également préférable d'utiliser des fruits de saison.</p>
        </div>
        <a href="mesRecettes.php"><i class="far fa-heart"></i> Vos recettes favorites</a>
    </section>

    <section id="articles" class="row">
        <?php foreach($recipe as $value): ?>
        <article class="col-sm-12 col-md-6 col-xl-4">
        <a href="recipe.php?id=<?= $value['id'] ?>">
            <div style="background-image:url(<?= $value['imgSrcRecipe'] ?>)">
                <img class="fav" src="img/icons/emptyheart.png" alt="heart">
            </div>
            <h2><span><?= $value["recipeName"] ?></span></h2>
            </a>
        </article>
        <?php endforeach; ?>
    </section>
</main>


</body>
</html>