<main id="recipe">
    <div><img src='<?= $recipe["imgSrcRecipe"] ?>' alt="Smoothie"></div>
    <h1 class="text-uppercase"><?= $recipe["recipeName"] ?></h1>
    <section>  
    <a class="btn recipe" href="#"><i class="fas fa-heart"></i> Ajouter cette recette en favoris</a>
        <article class="ingredient col-12 col-lg-4">
            <h3><span>INGREDIENTS</span></h3>
            <div>
                <?= $recipe["ingredientRecipe"] ?>
            </div>
        </article>
        <article class="recipe col-12 col-lg-8">
            <?= $recipe["descriptionRecipe"] ?>
        </article>
    </section>
</main>    