<!DOCTYPE html>
<html lang="fr">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.6.1/css/all.css" integrity="sha384-gfdkjb5BdAXd+lj+gudLWI+BXq4IuLW5IT+brZEZsLFm++aCMlF1V92rMkPaX4PP" crossorigin="anonymous">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css">
    <link href="https://fonts.googleapis.com/css?family=Montserrat:400,800|Nixie+One" rel="stylesheet">
    <link rel="stylesheet" href="css/str.css">
    <title>Smoothies</title>
</head>
<body>
    
<main id="recettes" class="container">
    <section id="presentation">
        <div class="imageSmoothie col-6">
        </div>
        <div class="titre col-6">
            <h1>Nos smoothies</h1>
        </div>
        <div class="para">
            <p>Des smoothies fait maison, avec des produits bio et de saison. Au plus possible nous favorisons les producteurs locaux afin de vous proposer des produits Eco-responsable, et bla bla bla.</p>
        </div>
        <a href="lebar.php">Venez déguster nos smoothies</a>
    </section>

    <section id="articles" class="row">
        <?php foreach($user as $value): ?>
        <article class="col-sm-12 col-md-6 col-xl-4">
            <div style="background-image:url(<?= $value['imgSrc'] ?>)"></div>
            <h2><span><?= $value["productName"] ?></span></h2>
        </article>
        <?php endforeach; ?>
    </section>
</main>


</body>
</html>