<main id="recettes" class="container">
    <section id="presentation">
        <div class="imageSmoothie col-6">
        </div>
        <div class="titre col-6">
            <h1>Nos smoothies</h1>
        </div>
        <div class="para">
            <p>Des smoothies fait maison, avec des produits bio et de saison. Au plus possible nous favorisons les producteurs locaux afin de vous proposer des produits Eco-responsable, et bla bla bla.</p>
        </div>
        <a href="lebar.php">Venez déguster nos smoothies</a>
    </section>

    <section id="articles" class="row">
        <?php foreach($user as $value): ?>
        <article class="col-sm-12 col-md-6 col-xl-4">
            <div style="background-image:url(<?= $value['imgSrc'] ?>)"></div>
            <h2><span><?= $value["productName"] ?></span></h2>
        </article>
        <?php endforeach; ?>
    </section>
</main>
